name: Build and Deploy to Azure

on:
  push:
    branches: 
      - main  # Change if needed

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # You can use '8.0.x' if you're not upgrading (not recommended)

      - name: Create nuget.config with DevExpress feed
        shell: bash
        run: |
          echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>
          <configuration>
          <packageSources>
            <add key=\"nuget.org\" value=\"https://api.nuget.org/v3/index.json\" protocolVersion=\"3\" />
            <add key=\"DevExpress\" value=\"https://nuget.devexpress.com/${{ secrets.DEVEXPRESS_NUGET_KEY }}/api\" />
          </packageSources>
          </configuration>" > nuget.config

      - name: Restore dependencies
        run: dotnet restore PresTrustDevExReportsService/Src/APIs/PresTrust.DevExReports.API/PresTrust.DevExReports.API.csproj --configfile nuget.config

      - name: Build the project
        run: dotnet build PresTrustDevExReportsService/Src/APIs/PresTrust.DevExReports.API/PresTrust.DevExReports.API.csproj --no-restore --configuration Release

      - name: Publish the project
        run: dotnet publish PresTrustDevExReportsService/Src/APIs/PresTrust.DevExReports.API/PresTrust.DevExReports.API.csproj --configuration Release --output ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'api-greencounty-reports'  # 🔁 Replace with your Azure Web App name
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_26D57BB4319940FDBF54323B6AD649CF }}
          package: ./publish

